export const rowData = [
  {
    make: "Tesla",
    model: "Model Y",
    price: 64950,
    electric: true,
    availableDate: "2023-01-15",
    country: "United States",
  },
  {
    make: "Ford",
    model: "F-150",
    price: 33850,
    electric: false,
    availableDate: "2023-03-20",
    country: "United States",
  },
  {
    make: "Toyota",
    model: "Corolla",
    price: 29600,
    electric: false,
    availableDate: "2023-02-28",
    country: "Japan",
  },
  {
    make: "BMW",
    model: "i4",
    price: 55000,
    electric: true,
    availableDate: "2023-04-10",
    country: "Germany",
  },
  {
    make: "Mercedes",
    model: "EQS",
    price: 104400,
    electric: true,
    availableDate: "2023-05-01",
    country: "Germany",
  },
  {
    make: "Honda",
    model: "Civic",
    price: 23950,
    electric: false,
    availableDate: "2023-01-25",
    country: "Japan",
  },
  {
    make: "Jaguar",
    model: "I-PACE",
    price: 71300,
    electric: true,
    availableDate: "2023-06-12",
    country: "United Kingdom",
  },
  {
    make: "Land Rover",
    model: "Defender",
    price: 53500,
    electric: false,
    availableDate: "2023-07-20",
    country: "United Kingdom",
  },
  {
    make: "Kia",
    model: "EV6",
    price: 48700,
    electric: true,
    availableDate: "2023-02-18",
    country: "South Korea",
  },
  {
    make: "Hyundai",
    model: "Ioniq 5",
    price: 41450,
    electric: true,
    availableDate: "2023-03-05",
    country: "South Korea",
  },
  {
    make: "Holden",
    model: "Commodore",
    price: 45000,
    electric: false,
    availableDate: "2022-11-05",
    country: "Australia",
  },
  {
    make: "Volkswagen",
    model: "Golf",
    price: 23195,
    electric: false,
    availableDate: "2023-08-01",
    country: "Germany",
  },
];
